cmd: console: add missing includes
Avoid errors

    ../cmd/console.c:51:15: error: implicit declaration of function
    ‘uclass_get_device’ [-Wimplicit-function-declaration]
       51 |         ret = uclass_get_device(UCLASS_VIDEO, 0, &dev);

    ../cmd/console.c:55:9: error: implicit declaration of function ‘video_clear’ [-Wimplicit-function-declaration]
       55 |         video_clear(dev);
          |         ^~~~~~~~~~~

Fixes: cf7ee6d23835 ("Fix some issues and change the logo background color. 1. Fix the issue where GRUB cannot return to the U-Boot command line after exiting. 2. Fix the support for vidconsole. 3. Change the logo to a black background.")
Signed-off-by: Heinrich Schuchardt <heinrich.schuchardt@canonical.com>