board: fix jh7110_gpio_init -Wint-conversion
Avoid error

../board/starfive/visionfive2/starfive_visionfive2.c:
    In function ‘jh7110_gpio_init’:
    ../board/starfive/visionfive2/starfive_visionfive2.c:430:19: error:
    passing argument 2 of ‘writel’ makes pointer from integer without a
    cast [-Wint-conversion]
      430 |         writel(0, 0x13040200);
          |                   ^~~~~~~~~~
          |                   |
          |                   int

Fixes: ade2e949129c ("add switch gpio init.")
Signed-off-by: Heinrich Schuchardt <heinrich.schuchardt@canonical.com>