drivers/video: missing conversion in saif_set_reg
Avoid errors

    ../drivers/video/starfive/sf_vop.c: In function ‘saif_set_reg’:
    ../drivers/video/starfive/sf_vop.c:48:17: error:
    passing argument 1 of ‘readl’ makes pointer from integer
    without a cast [-Wint-conversion]
       48 |     tmp = readl(addr);
          |                 ^~~~
          |                 |
          |                 uint32_t {aka unsigned int}

    ../drivers/video/starfive/sf_vop.c:51:16: error:
    passing argument 2 of ‘writel’ makes pointer from integer
    without a cast [-Wint-conversion]
       51 |     writel(tmp,addr);
          |                ^~~~
          |                |
          |                uint32_t {aka unsigned int}

Fixes: 26a31fa6bc9d ("uboot: hdmi logo causes kernel hdmi unstable")
Signed-off-by: Heinrich Schuchardt <heinrich.schuchardt@canonical.com>